name: Check and publish

on:
  release:
    types: [created]

  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install black flake8 isort
      - run: black --version
      - run: isort --version
      - run: flake8 --version
      - run: isort --check .
      - run: black --check .
      - run: flake8 .

  deploy:

    name: Test and upload to Pypi
    needs: quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - uses: actions/setup-node@v2
      with:
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

    - name: Build javascript frontend
      working-directory: ./frontend
      run: |
        npm install
        npm test
        npm run build
        mv build ../climetlab_script_web/build

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'


    - name: Build python package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python setup.py sdist

    - name: list package content
      run: tar tvf dist/climetlab-script-web-*.tar.gz
                                          
    - name: Install climetlab
      run: pip install climetlab

    - name: Install python package
      run: pip install dist/climetlab-script-web-*.tar.gz

    - name: Run tests
      run: echo 'setup tests. pytest or other'

    - name: Check version
      if: ${{ github.event_name == 'release' }}
      run: |
        release=${GITHUB_REF##*/}
        version=$(python setup.py --version)
        test "$release" == "$version"

    - name: Publish
      if: ${{ github.event_name == 'release' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
