name: Check and publish

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install black flake8 isort
      - run: black --version
      - run: isort --check .
      - run: black --check .
      - run: flake8 .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
          cache: 'npm'
    - run: npm install
    - run: npm test

    - name: Install javascript build dependencies
      working-directory: ./reactjs
      run: |
        npm run build

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'


    # - name: Install python build dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install setuptools wheel twine

    # - name: Build python package
    #   run: |
    #     python setup.py sdist
